"""Create CostCenter Model

Revision ID: 761ef4a384bd
Revises: 80bef4cd7b13
Create Date: 2025-10-03 22:57:38.599660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '761ef4a384bd'
down_revision: Union[str, Sequence[str], None] = '80bef4cd7b13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_branchcode', 'cost_centers', ['BranchCode'], unique=False)
    op.create_index(op.f('ix_cost_centers_BranchCode'), 'cost_centers', ['BranchCode'], unique=False)
    op.create_index(op.f('ix_cost_centers_id'), 'cost_centers', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cost_centers_id'), table_name='cost_centers')
    op.drop_index(op.f('ix_cost_centers_BranchCode'), table_name='cost_centers')
    op.drop_index('idx_branchcode', table_name='cost_centers')
    # ### end Alembic commands ###
