"""create Sub_GlCode model

Revision ID: 80bef4cd7b13
Revises: 
Create Date: 2025-10-03 21:11:03.491767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80bef4cd7b13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_headers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CostCenterID', sa.String(), nullable=False),
    sa.Column('SubHeadID', sa.String(), nullable=True),
    sa.Column('SubGLCode', sa.String(), nullable=False),
    sa.Column('SubHead', sa.String(), nullable=True),
    sa.Column('Region', sa.String(), nullable=True),
    sa.Column('BCode', sa.String(), nullable=True),
    sa.Column('BName', sa.String(), nullable=True),
    sa.Column('BudgetID', sa.String(), nullable=True),
    sa.Column('Head', sa.String(), nullable=True),
    sa.Column('HeadID', sa.String(), nullable=True),
    sa.Column('CostCenter', sa.String(), nullable=True),
    sa.Column('BudgetAmount', sa.String(), nullable=True),
    sa.Column('ValidityDate', sa.String(), nullable=True),
    sa.Column('Description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_CostCenterID', 'csv_headers', ['CostCenterID'], unique=False)
    op.create_index('idx_CostCenterID_SubGLCode', 'csv_headers', ['CostCenterID', 'SubGLCode'], unique=False)
    op.create_index(op.f('ix_csv_headers_CostCenterID'), 'csv_headers', ['CostCenterID'], unique=False)
    op.create_index(op.f('ix_csv_headers_SubGLCode'), 'csv_headers', ['SubGLCode'], unique=False)
    op.create_index(op.f('ix_csv_headers_id'), 'csv_headers', ['id'], unique=False)
    op.create_table('sub_gl_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('SubGLCode', sa.String(), nullable=False),
    sa.Column('SubHeadID', sa.String(), nullable=True),
    sa.Column('SubHeadName', sa.String(), nullable=True),
    sa.Column('Head', sa.String(), nullable=True),
    sa.Column('HeadID', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_SubGLCode', 'sub_gl_codes', ['SubGLCode'], unique=False)
    op.create_index(op.f('ix_sub_gl_codes_SubGLCode'), 'sub_gl_codes', ['SubGLCode'], unique=False)
    op.create_index(op.f('ix_sub_gl_codes_id'), 'sub_gl_codes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sub_gl_codes_id'), table_name='sub_gl_codes')
    op.drop_index(op.f('ix_sub_gl_codes_SubGLCode'), table_name='sub_gl_codes')
    op.drop_index('idx_SubGLCode', table_name='sub_gl_codes')
    op.drop_table('sub_gl_codes')
    op.drop_index(op.f('ix_csv_headers_id'), table_name='csv_headers')
    op.drop_index(op.f('ix_csv_headers_SubGLCode'), table_name='csv_headers')
    op.drop_index(op.f('ix_csv_headers_CostCenterID'), table_name='csv_headers')
    op.drop_index('idx_CostCenterID_SubGLCode', table_name='csv_headers')
    op.drop_index('idx_CostCenterID', table_name='csv_headers')
    op.drop_table('csv_headers')
    # ### end Alembic commands ###
