"""Update Column Types

Revision ID: 96f67f96d53b
Revises: 13fec22d81be
Create Date: 2025-09-02 00:25:55.387152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96f67f96d53b'
down_revision: Union[str, Sequence[str], None] = '13fec22d81be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_CostCenterID'), table_name='csv_headers')
    op.drop_index(op.f('idx_CostCenterID_SubGLCode'), table_name='csv_headers')
    op.drop_index(op.f('ix_csv_headers_CostCenterID'), table_name='csv_headers')
    op.drop_index(op.f('ix_csv_headers_SubGLCode'), table_name='csv_headers')
    op.drop_index(op.f('ix_csv_headers_id'), table_name='csv_headers')
    op.drop_table('csv_headers')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('csv_headers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('CostCenterID', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('SubHeadID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SubGLCode', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('SubHead', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('BCode', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('BName', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('BudgetID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Head', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('HeadID', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('CostCenter', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('BudgetAmount', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ValidityDate', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('csv_headers_pkey'))
    )
    op.create_index(op.f('ix_csv_headers_id'), 'csv_headers', ['id'], unique=False)
    op.create_index(op.f('ix_csv_headers_SubGLCode'), 'csv_headers', ['SubGLCode'], unique=False)
    op.create_index(op.f('ix_csv_headers_CostCenterID'), 'csv_headers', ['CostCenterID'], unique=False)
    op.create_index(op.f('idx_CostCenterID_SubGLCode'), 'csv_headers', ['CostCenterID', 'SubGLCode'], unique=False)
    op.create_index(op.f('idx_CostCenterID'), 'csv_headers', ['CostCenterID'], unique=False)
    # ### end Alembic commands ###
